In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [2]:
ds = pd.read_csv("data.csv")
ds

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN


In [3]:
ds['name'] = ds['name'].str.strip()
ds['name'].unique()

<ArrowStringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
             'Maruti Suzuki Alto 800 Vxi',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
 ...
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
  'Maruti Suzuki Alto 800 Select Variant',
             'Maruti Suzuki Ritz VXI ABS',
                       'tata zest 2017 f',
              'Tata Indica V2 DLE BS III',
                                     'Ta',
                    'Tata Zest XM Diesel',
               'Honda Amaze 1.2 E i VTEC',
              'Chevrolet Sail 1.2 LT ABS']
Length: 525, dtype: str

In [4]:
len(ds["name"].unique())

525

In [5]:
len(ds["company"].unique())

48

In [6]:
ds["company"].unique()

<ArrowStringArray>
[   'Hyundai',   'Mahindra',     'Maruti',       'Ford',      'Skoda',
       'Audi',     'Toyota',    'Renault',      'Honda',     'Datsun',
 'Mitsubishi',       'Tata', 'Volkswagen',          'I',  'Chevrolet',
       'Mini',        'BMW',     'Nissan',  'Hindustan',       'Fiat',
 'Commercial',     'MARUTI',      'Force',   'Mercedes',       'Land',
     'Yamaha',    'selling',     'URJENT',      'Swift',       'Used',
     'Jaguar',       'Jeep',       'tata',       'Sale',       'very',
      'Volvo',          'i',       '2012',       'Well',        'all',
          '7',          '9',    'scratch',     'urgent',       'sell',
       'TATA',        'Any',       'Tara']
Length: 48, dtype: str

In [7]:
ds["fuel_type"].unique()

<ArrowStringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [8]:
ds["year"].unique()

<ArrowStringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [9]:
ds["Price"].unique()

<ArrowStringArray>
[       '80,000',      '4,25,000', 'Ask For Price',      '3,25,000',
      '5,75,000',      '1,75,000',      '1,90,000',      '8,30,000',
      '2,50,000',      '1,82,000',
 ...
        '42,000',      '1,89,000',      '1,62,000',        '35,999',
     '29,00,000',        '39,999',        '50,500',      '5,10,000',
      '8,60,000',      '5,00,001']
Length: 274, dtype: str

In [10]:
ds["kms_driven"].unique()

<ArrowStringArray>
[  '45,000 kms',       '40 kms',   '22,000 kms',   '28,000 kms',
   '36,000 kms',   '59,000 kms',   '41,000 kms',   '25,000 kms',
   '24,530 kms',   '60,000 kms',
 ...
   '60,123 kms',   '38,900 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 259, dtype: str

In [11]:
ds['year'].unique()

<ArrowStringArray>
['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016', '2010',
 '2017', '2008', '2011', '2019', '2009', '2005', '2000',  '...', '150k',
 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs', 'sale', '1995', 'ara)',
 '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry',  'Eon', 'o...',
 'ture',  'emi',  'car', 'able',  'no.', 'd...', 'SALE', 'digo', 'sell',
 'd Ex', 'n...', 'e...', 'D...', ', Ac', 'go .', 'k...', 'o c4', 'zire',
 'cent', 'Sumo',  'cab', 't xe',  'EV2', 'r...', 'zest']
Length: 61, dtype: str

In [12]:
ds['year'] = pd.to_numeric(ds['year'],errors='coerce')

In [13]:
ds['year'].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000.,   nan, 2003.,
       2004., 1995., 2002., 2001.])

In [14]:
ds.dropna(subset=['year'],inplace=True)

In [15]:
ds['year'].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000., 2003., 2004.,
       1995., 2002., 2001.])

In [16]:
ds['Price']

0             80,000
1           4,25,000
2      Ask For Price
3           3,25,000
4           5,75,000
           ...      
886         3,00,000
888         2,60,000
889         3,90,000
890         1,80,000
891         1,60,000
Name: Price, Length: 842, dtype: str

In [17]:
ds['Price'] = ds['Price'].str.replace(",","")

In [18]:
ds['Price']

0              80000
1             425000
2      Ask For Price
3             325000
4             575000
           ...      
886           300000
888           260000
889           390000
890           180000
891           160000
Name: Price, Length: 842, dtype: str

In [19]:
ds['Price'] = pd.to_numeric(ds['Price'],errors='coerce')

In [20]:
ds['Price'].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  275000.,  285000.,  3400

In [21]:
ds.dropna(subset=['Price'],inplace=True)

In [22]:
ds['Price'].unique()

array([  80000.,  425000.,  325000.,  575000.,  175000.,  190000.,
        830000.,  250000.,  182000.,  315000.,  415000.,  320000.,
       1000000.,  500000.,  350000.,  160000.,  310000.,   75000.,
        100000.,  290000.,   95000.,  180000.,  385000.,  105000.,
        650000.,  689999.,  448000.,  549000.,  501000.,  489999.,
        280000.,  349999.,  284999.,  345000.,  499999.,  235000.,
        249999., 1475000.,  395000.,  220000.,  170000.,   85000.,
        200000.,  570000.,  110000.,  448999., 1891111.,  159500.,
        344999.,  449999.,  865000.,  699000.,  375000.,  224999.,
       1200000.,  195000.,  351000.,  240000.,   90000.,  155000.,
        600000.,  189500.,  210000.,  390000.,  135000., 1600000.,
        701000.,  265000.,  525000.,  372000.,  635000.,  550000.,
        485000.,  329500.,  251111.,  569999.,   69999.,  299999.,
        399999.,  450000.,  270000.,  158400.,  179000.,  125000.,
        299000.,  150000.,  275000.,  285000.,  340000.,   700

In [23]:
ds['Price'] = ds['Price'].astype(int)

In [24]:
ds['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  275000,  285000,  340000,   70000,  289999,
        849999,  749999,  274999,  984999,  599999,  244999,  474999,
        245000,  169

In [25]:
ds['kms_driven'].unique()

<ArrowStringArray>
[  '45,000 kms',       '40 kms',   '28,000 kms',   '36,000 kms',
   '41,000 kms',   '25,000 kms',   '24,530 kms',   '60,000 kms',
   '30,000 kms',   '32,000 kms',
 ...
   '33,400 kms',   '60,123 kms', '1,37,495 kms',   '91,200 kms',
 '1,46,000 kms', '1,00,800 kms',    '2,100 kms',    '2,500 kms',
 '1,32,000 kms',       'Petrol']
Length: 250, dtype: str

In [26]:
ds['kms_driven'] = ds['kms_driven'].str.replace("kms","")

In [27]:
ds['kms_driven'] = ds['kms_driven'].str.replace(",","")

In [28]:
ds['kms_driven'].unique()

<ArrowStringArray>
[ '45000 ',     '40 ',  '28000 ',  '36000 ',  '41000 ',  '25000 ',  '24530 ',
  '60000 ',  '30000 ',  '32000 ',
 ...
  '33400 ',  '60123 ', '137495 ',  '91200 ', '146000 ', '100800 ',   '2100 ',
   '2500 ', '132000 ',  'Petrol']
Length: 250, dtype: str

In [29]:
ds['kms_driven'] = pd.to_numeric(ds['kms_driven'],errors='coerce')

In [30]:
ds.dropna(subset=['kms_driven'],inplace=True)

In [31]:
ds['kms_driven'].unique()

array([4.50000e+04, 4.00000e+01, 2.80000e+04, 3.60000e+04, 4.10000e+04,
       2.50000e+04, 2.45300e+04, 6.00000e+04, 3.00000e+04, 3.20000e+04,
       4.86600e+04, 4.00000e+03, 1.69340e+04, 4.30000e+04, 3.55500e+04,
       3.95220e+04, 3.90000e+04, 5.50000e+04, 7.20000e+04, 1.59750e+04,
       7.00000e+04, 2.34520e+04, 3.55220e+04, 4.85080e+04, 1.54870e+04,
       8.20000e+04, 2.00000e+04, 6.80000e+04, 3.80000e+04, 2.70000e+04,
       3.30000e+04, 4.60000e+04, 1.60000e+04, 4.70000e+04, 3.50000e+04,
       3.08740e+04, 1.50000e+04, 2.96850e+04, 1.30000e+05, 1.90000e+04,
       5.40000e+04, 1.30000e+04, 3.82000e+04, 2.20000e+04, 5.00000e+04,
       1.35000e+04, 3.60000e+03, 4.58630e+04, 6.05000e+04, 1.25000e+04,
       1.80000e+04, 1.33490e+04, 2.90000e+04, 4.40000e+04, 4.20000e+04,
       1.40000e+04, 4.90000e+04, 3.62000e+04, 5.10000e+04, 1.04000e+05,
       3.33330e+04, 3.36000e+04, 5.60000e+03, 7.50000e+03, 2.60000e+04,
       2.43300e+04, 6.54800e+04, 2.00000e+05, 5.90000e+04, 9.900

In [32]:
ds

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006.0,425000,40.0,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000,36000.0,Diesel
6,Ford Figo,Ford,2012.0,175000,41000.0,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011.0,270000,50000.0,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009.0,110000,30000.0,Diesel
886,Toyota Corolla Altis,Toyota,2009.0,300000,132000.0,Petrol
888,Tata Zest XM Diesel,Tata,2018.0,260000,27000.0,Diesel


In [33]:
for i in ds.index:
    company = ds.loc[i,'company']
    name = ds.loc[i,'name']
    name = name.replace(company,"")
    ds.loc[i,'name'] = name
ds['name'] = ds['name'].str.strip()

In [34]:
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000,45000.0,Petrol
1,Jeep CL550 MDI,Mahindra,2006.0,425000,40.0,Diesel
3,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000,28000.0,Petrol
4,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000,36000.0,Diesel
6,Figo,Ford,2012.0,175000,41000.0,Diesel
...,...,...,...,...,...,...
883,Suzuki Ritz VXI ABS,Maruti,2011.0,270000,50000.0,Petrol
885,Indica V2 DLE BS III,Tata,2009.0,110000,30000.0,Diesel
886,Corolla Altis,Toyota,2009.0,300000,132000.0,Petrol
888,Zest XM Diesel,Tata,2018.0,260000,27000.0,Diesel


In [35]:
ds.info()

<class 'pandas.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        817 non-null    str    
 1   company     817 non-null    str    
 2   year        817 non-null    float64
 3   Price       817 non-null    int64  
 4   kms_driven  817 non-null    float64
 5   fuel_type   816 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 100.6 KB


In [36]:
ds.dropna(inplace=True)

In [37]:
ds.info()

<class 'pandas.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        816 non-null    str    
 1   company     816 non-null    str    
 2   year        816 non-null    float64
 3   Price       816 non-null    int64  
 4   kms_driven  816 non-null    float64
 5   fuel_type   816 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 68.3 KB


In [38]:
ds['Price'].max()

np.int64(8500003)

In [39]:
ds = ds[ds['Price']>=50000]

In [40]:
ds

,name,company,year,Price,kms_driven,fuel_type
0,Santro Xing XO eRLX Euro III,Hyundai,2007.0,80000,45000.0,Petrol
1,Jeep CL550 MDI,Mahindra,2006.0,425000,40.0,Diesel
3,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000,28000.0,Petrol
4,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000,36000.0,Diesel
6,Figo,Ford,2012.0,175000,41000.0,Diesel
...,...,...,...,...,...,...
883,Suzuki Ritz VXI ABS,Maruti,2011.0,270000,50000.0,Petrol
885,Indica V2 DLE BS III,Tata,2009.0,110000,30000.0,Diesel
886,Corolla Altis,Toyota,2009.0,300000,132000.0,Petrol
888,Zest XM Diesel,Tata,2018.0,260000,27000.0,Diesel


In [41]:
ds = ds[ds['Price']<8500003]

In [42]:
ds['Price'].max()

np.int64(3100000)

In [43]:
ds.duplicated().value_counts()

False    708
True      92
Name: count, dtype: int64

In [44]:
ds.drop_duplicates(inplace=True)

In [45]:
ds.duplicated().value_counts()

False    708
Name: count, dtype: int64

In [46]:
ds.to_csv("clean_data.csv", index=False)

In [47]:
ds = pd.read_csv("clean_data.csv")

In [48]:
ds.info()

<class 'pandas.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   name        708 non-null    str    
 1   company     708 non-null    str    
 2   year        708 non-null    float64
 3   Price       708 non-null    int64  
 4   kms_driven  708 non-null    float64
 5   fuel_type   708 non-null    str    
dtypes: float64(2), int64(1), str(3)
memory usage: 53.7 KB
